# AUTO-GENERATED from fdl_api.yaml — DO NOT EDIT
"""FDL Core enum constants for ctypes FFI."""

# fdl_rounding_mode_t
FDL_ROUNDING_MODE_UP = 0
FDL_ROUNDING_MODE_DOWN = 1
FDL_ROUNDING_MODE_ROUND = 2

# fdl_rounding_even_t
FDL_ROUNDING_EVEN_WHOLE = 0
FDL_ROUNDING_EVEN_EVEN = 1

# fdl_geometry_path_t
FDL_GEOMETRY_PATH_CANVAS_DIMENSIONS = 0
FDL_GEOMETRY_PATH_CANVAS_EFFECTIVE_DIMENSIONS = 1
FDL_GEOMETRY_PATH_FRAMING_PROTECTION_DIMENSIONS = 2
FDL_GEOMETRY_PATH_FRAMING_DIMENSIONS = 3

# fdl_fit_method_t
FDL_FIT_METHOD_WIDTH = 0
FDL_FIT_METHOD_HEIGHT = 1
FDL_FIT_METHOD_FIT_ALL = 2
FDL_FIT_METHOD_FILL = 3

# fdl_halign_t
FDL_HALIGN_LEFT = 0
FDL_HALIGN_CENTER = 1
FDL_HALIGN_RIGHT = 2

# fdl_valign_t
FDL_VALIGN_TOP = 0
FDL_VALIGN_CENTER = 1
FDL_VALIGN_BOTTOM = 2

